### ISSUE TITLE
P1: Collapse the map options down (to the bottom of the screen) instead of up

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#58]

**Comment by njmattes** [comment]
My gut reaction to this is that it's a bad idea—because you're moving the clickable target. I understand the impetus for it I think—to get the options out of the way when they're collapsed. And on the face of it, that makes a lot of sense. But it changes the fundamental nature of *how* a window collapses and how the user is accustomed to working with windows. 

To be fair, a window collapsing into its menu bar is pretty old school. I don;t know how it works on a Windows or *nix desktop, but on OS X minimizing a window places it in the dock. The menubar is no longer floating around the desktop. So, presuming that we move the ± zoom buttons to the edge of the screen (a la Google), eventually, minimizing the options pane could 'dock' it against the ±. Same for legend. This will require cookies to track options placement (see issue #59).

**Comment by njmattes** [comment]
Closing this as it's become redundant with #71
