### ISSUE TITLE
P1: Default the legend and map option positions to the right edge of the screen (top right and bottom right corners)

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#59]

**Comment by njmattes** [comment]
Using the screen for this is probably a bad idea because the size of screens changes so much. E.g. when someone is using a 30-inch monitor, this would place the main UI elements quite a distance from the map. That seems to be addressing one problem by creating another. 

We might be better served by creating a cookie that stores the user's preferences—map zoom level, lon/lat of the center, placement and visibility of options and legend, etc. This way a user can place things where they want them (it's rather easy after all), and then not have to keep doing that every time they use the map.

**Comment by bkleeman** [comment]
Sounds good to me. Hard to come up with a universal/sensible default given the way the UI is structured. And I'm concerned that the positions requested aren't really going to look very good on any display size.

**Comment by njmattes** [comment]
Closing this as it's become redundant with #71
