### ISSUE TITLE
P2: When I click on a spot on the map, center the map on that spot

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#62]

**Comment by njmattes** [comment]
I'm not convinced this is a good idea for a feature. It seems like a pretty invasive event (physically moving the map and changing its focal point) to attach to such an innocuous event (a mouse click). 

If rapidly centering the map without dragging it is an important feature, I'd attach it to a more intentional event (e.g. a double-click). But I'd be more inclined to mimic the behavior of Google Maps—double-click zooms, and single-click places a marker. In our case, eventually single-click will select an object on the map. And in that case I certainly wouldn't move the map because the user may want to click on other nearby objects to make a comparison. And if the maps is in constant motion, well, we can all imagine that.

**Comment by njmattes** [comment]
I'm closing this. If at some point we decide this is a good idea we can reopen.
