### ISSUE TITLE
mousedown event bubbling from checkboxes up to options options pane.

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#63]

**Comment by njmattes** [comment]
I think that this isn't actually the problem. My hunch is that the problem here is that very small motions of the mouse trigger the drag event on the map options pane. And this drag event is blocking the change event on the checkbox. I think that what really needs to happen is that we need to 'debounce' the drag event, but in the spatial domain rather than the time domain. 

If the issue in the title is actually the issue, it'll probably take some serious intervention. For now though I think I'd reject this issue and open another one about debouncing the dragging of the options pane. And if that doesn't solved the problem as perceived, we could then consider looking into event priorities and such.

**Comment by njmattes** [comment]
Actually, this is probably fixable by calling `stopPropagation()` on the `mousedown` event listener attached to the checkboxes to stop that event from bubbling up to the options pane.

**Comment by njmattes** [comment]
Fixed in new branch [`fix-checkbox-not-checking`](https://github.com/RDCEP/energy-maps/tree/fix-checkbox-not-checking). Ben I'm leaving this unmerged so you can see the fix if it's interesting. Feel free to reassign it back to me if you want me to merge into `dev`.

**Comment by njmattes** [comment]
Merged.
